name: Telegram Bot 24/7

on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:  # Ручной запус

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Create data directory
      run: mkdir -p data
      
    - name: Run Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        SCHEDULE_URL: https://edu.tgpi.ru
      run: |
        echo "🚀 Запуск бота..."
        go run main.go &
        BOT_PID=$!
        echo "✅ Бот запущен с PID: $BOT_PID"
        
        # Держим бота живым 5 минут
        sleep 280
        
        # Убиваем перед следующим запуском
        kill $BOT_PID 2>/dev/null || true
        echo "✅ Бот остановлен, ждем следующего запуска..."
